### ISSUE TITLE
I wonder how energy for fine-grained behavior is reflected in timeloop-accelergy.

### ISSUE THREAD

**Issue by cjw9202** [jsemer/timeloop-accelergy-tutorial#1]
Hi. First of all, thank you for your great works. 
I have a question about your works.
One of the contributions of the Accelergy paper is to support energy for fine-grained actions. But I think Timeloop doesn't define fine-grained behaviors like gated_MAC or repeated/random access.
Can you tell me how the energy of fine-grained actions is reflected when I run Accelergy and Timeloop together?

Thanks

**Comment by nellie-wu** [comment]
Thanks for bringing up the question! 
You are correct that Timeloop does not define the fine-grained behaviors of the components. In fact, the current version of Timeloop-Accelergy infrastructure does not reflect the energy differences of the fine-grained behaviors yet; Timeloop currently only captures coarse-grained actions. That is something we aim to address as future work.
