### ISSUE TITLE
Errors during Image build

### ISSUE THREAD

**Issue by sgodey** [jsemer/timeloop-accelergy-tutorial#10]
I am getting the below errors when I am trying to build a docker image. Any thoughts?

![build_err](https://github.com/Accelergy-Project/timeloop-accelergy-tutorial/assets/24397010/174fc7b7-cf13-4847-93e7-8e4428f8172a)

My command is "docker build -t tutorial_withvi .". I am trying to add VI to the image. Below are errors in text.

 => ERROR [stage-1 3/7] COPY src/ /usr/local/src/                                                                  0.0s
 => ERROR [stage-1 4/7] COPY ./bin/refresh-exercises /usr/local/bin                                                0.0s
 => CACHED [stage-1 5/7] RUN apt-get install vim                                                                   0.0s
 => ERROR [stage-1 6/7] COPY docker-entrypoint.sh /usr/local/bin

**Comment by tanner-andrulis** [comment]
This repo is outdated. Please try with the https://github.com/Accelergy-Project/timeloop-accelergy-exercises
