### ISSUE TITLE
Key not found error

### ISSUE THREAD

**Issue by TravisDai** [jsemer/timeloop-accelergy-tutorial#3]
Hi, I am using docker to run the timeloop & accelergy in the diretory "/exercises/timeloop+accelergy" and when I am using the command (timeloop-mapper arch/eyeriss_like-int16.arch.yaml \
                arch/components/*.yaml \
                prob/prob.yaml \
                mapper/mapper.yaml \
                constraints/*.yaml), I got the following errors:
 
Problem configuration complete.
ERROR: key not found: arithmetic, at line: 0

Do you know what seems to be the problem?

Thanks.
Travis

**Comment by nellie-wu** [comment]
Unfortunately, I cannot reproduce the error you have with the same setup (with *.yaml as the last part of the paths for components and constraints). Please see below a screenshot of the output on my end. 
![capture](https://user-images.githubusercontent.com/7805840/100148949-71c44a80-2e6b-11eb-9522-99c8162f2aef.PNG)
If you are able to run the other exercises successfully, this example should not have an issue.

**Comment by nivi1501** [comment]
I am facing the same issue. @TravisDai how did you resolve it?

**Comment by nellie-wu** [comment]
Thanks for bringing up this issue.

I think this is probably due to a typo in the readme, instead of `arch/eyeriss_like-int16.arch.yaml`, please try `arch/eyeriss_like-int16.yaml`.  

You can also do `ls arch/` to see the files names in the `arch ` folder. 

We have updated the readme as well.
