### ISSUE TITLE
Error when using scons to build timeloop

### ISSUE THREAD

**Issue by ChenpingHU** [jsemer/timeloop-accelergy-tutorial#4]
Hello, developers,

I was trying to install natively timeloop-accelergy on my centos following the official instructions, but an error came up when I run "scons -j4 --accelergy --static", the error is :"  g++: error: unrecognized command line option '-std=c++14'  ". Could you please help me to fix this issue? Thank you very much!

**Comment by nellie-wu** [comment]
This probably means your compiler version is not up-to-date. See here: https://github.com/NVlabs/timeloop/issues/69
