### ISSUE TITLE
Error while building timeloop-accelergy

### ISSUE THREAD

**Issue by ChenpingHU** [jsemer/timeloop-accelergy-tutorial#5]
Dear developers,

There is an error when I run the command **scon -j4 --accelergy --static**, and the error is like this:

**/usr/include/boost/multiprecision/cpp_int.hpp:175:4: error: right operand of shift expression ‘(1 << 63)’ is >= than the precision of the left operand [-fpermissive]
    BOOST_STATIC_CONSTANT(limb_type, sign_bit_mask = 1u << (limb_bits - 1));**

Do you have any solutions for this error? Thank you!

**Comment by nellie-wu** [comment]
It might be that your ubuntu version is not up to date. The code has been tested against Ubuntu18, libconfig 1.5+, gcc9.3/7.5. If all of you system requirements are met, please open an issue to the Timeloop repo, and we will address the problem from there.
