### ISSUE TITLE
Error while installing timeloop-accelergy in a non-standard location

### ISSUE THREAD

**Issue by kmchiti** [jsemer/timeloop-accelergy-tutorial#6]
Hi

I want to locally install timeloop-accelergy (without sudo access).  First, I installed all required libraries locally and then tried to install timeloop-accelergy using virtual environment. But I got an error when I run the command `scon -j4 --accelergy --static`. 
```
/usr/local/bin/ld: cannot find -lyaml-cpp
/usr/local/bin/ld: cannot find -lncurses
/usr/local/bin/ld: cannot find -ltinfo
/usr/local/bin/ld: cannot find -lgpm
collect2: error: ld returned 1 exit status
scons: *** [build/timeloop-design-space] Error 1
```
I followed this [link ](https://stackoverflow.com/questions/4678548/scons-headers-libraries-in-a-non-standard-location) to edit the SConstruct file in `timeloop-accelergy/accelergy-timeloop-infrastructure/src/timeloop/SConstruct` and set my local directory. But I got the same error! I didn't have any problem with installing timeloop-accelergy with sudo access in standard location. Do you have any idea for this error? Thanks!

**Comment by nellie-wu** [comment]
It seems that your local install path is not included in `LD_LIBRARY_PATH`.
