### ISSUE TITLE
Issue with replacing the mac unit with an adder

### ISSUE THREAD

**Issue by Olivier-Dopeli** [jsemer/timeloop-accelergy-tutorial#7]
Hello,

I am testing the exercises in the tutorial on Timeloop and Accelergy. All the exercises worked well. To better understand how Timeloop+Accelergy works, I am trying to modify the exercises.

To begin with, I tried to replace the arithmetic unit in the exercises: 
```
	- name: mac      |> - name: add
	  class: intmac  |>   class: intadder
```
But I get the following errors:

- For the exercise of timeloop+accelergy
`what():  vector::_M_range_check: __n (which is 40577184) >= this->size() (which is 6)
Aborted (core dumped) `

- For the exercise of accelergy: 04_eyeriss_like 
`ERROR: Cannot find corresponding entry for component eyeriss_like.PE[0].mac `

For the moment I don't understand why I can't replace the mac unit by an adder. 
The class: intadder is defined in the list of "primitive_component_libs.yaml" and there is no constraint to use the mac class.

Do you have any idea what I did wrong?

Thank you in advance

**Comment by nellie-wu** [comment]
You need to update the constraint file for timeloop+accelergy and update the action counts file for accelergy exercise 04.
